"""Shared fixtures. Tests run against the committed reference datasets in
data/reference (generated by the ingestion scripts, SPEC §12 M1)."""

from __future__ import annotations

import pytest

from besscalc.models import (
    BatterySpec,
    ConsumptionSpec,
    PVSpec,
    ScenarioConfig,
    SimulationRequest,
    SiteSpec,
)


@pytest.fixture
def battery_spec() -> BatterySpec:
    return BatterySpec(
        name="Test 10 kWh",
        capacity_kwh=10.0,
        power_kw=5.0,
        roundtrip_efficiency=0.92,
        depth_of_discharge=0.90,
        calendar_degradation_pct_yr=1.5,
        lifetime_years=15,
        price_dkk_installed=45000.0,
    )


@pytest.fixture
def request_pv(battery_spec) -> SimulationRequest:
    return SimulationRequest(
        battery=battery_spec,
        pv=PVSpec(kwp=6.0, orientation="S"),
        consumption=ConsumptionSpec(annual_kwh=5500.0, profile="base_ev"),
        site=SiteSpec(price_area="DK1", dso="n1"),
        scenario=ScenarioConfig(),
    )


@pytest.fixture
def request_no_pv(battery_spec) -> SimulationRequest:
    return SimulationRequest(
        battery=battery_spec,
        pv=None,
        consumption=ConsumptionSpec(annual_kwh=4500.0, profile="base"),
        site=SiteSpec(price_area="DK2", dso="radius"),
        scenario=ScenarioConfig(),
    )
